import React, { useEffect } from "react";
import Fade from "react-reveal";

import BibleVerse from "../json/landingPage.json";

import UserIcon from "../assets/images/userIcon.svg";

export default function LandingPageSecondSectionContent() {
  function fadeOut(element) {
    element.style.opacity = 1;

    (function fade() {
      if ((element.style.opacity -= 0.1) < 0) {
        element.style.display = "none";
      } else {
        requestAnimationFrame(fade);
      }
    })();
  }

  function fadeIn(element, display) {
    element.style.opacity = 0;
    element.style.display = display || "block";

    (function fade() {
      let val = parseFloat(element.style.opacity);
      if (!((val += 0.1) > 1)) {
        element.style.opacity = val;
        requestAnimationFrame(fade);
      }
    })();
  }

  function handleClick() {
    const verseArray = [...BibleVerse.bible.verse];
    const preachArray = [...BibleVerse.bible.preeches];
    for (let i = verseArray.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [verseArray[i], verseArray[j]] = [verseArray[j], verseArray[i]];
      [preachArray[i], preachArray[j]] = [preachArray[j], preachArray[i]];
    }
    const randomIndex = Math.floor(Math.random() * verseArray.length);
    const verse = verseArray[randomIndex];
    const preach = preachArray[randomIndex];

    const verseElement = document.querySelector(".sc-verse");
    const preachElement = document.querySelector(".sc-preach q");

    fadeOut(verseElement);
    fadeOut(preachElement);

    setTimeout(function () {
      verseElement.innerHTML = verse;
      preachElement.innerHTML = preach;

      fadeIn(verseElement);
      fadeIn(preachElement);
    }, 500);
  }

  window.onload = function () {
    document
      .querySelector(".sc-randomizer")
      .addEventListener("click", handleClick);
  };

  useEffect(() => {
    const randomizerButton = document.querySelector(".sc-randomizer");
    if (randomizerButton) {
      randomizerButton.addEventListener("click", handleClick);
    }

    return () => {
      if (randomizerButton) {
        randomizerButton.removeEventListener("click", handleClick);
      }
    };
  }, []);

  return (
    <div className="container">
      <div className="secondsection-content">
        <div className="col">
          <Fade bottom>
            <h4 className="sc-firstcontent">
              Welcome to{" "}
              <span className="sc-firstcontent-rgb">Youth GBI Oasis</span>, a
              community where we're{" "}
              <span className="sc-firstcontent-flicker">passionate</span> about
              mentoring teenagers{" "}
              <span className="sc-firstcontent-flicker">
                develop essential skills
              </span>{" "}
              from Church, for Church.
            </h4>
            <p className="sc-secondcontent">Daily Dose of Reflection</p>
            {/* THIS WILL BE AUTO GENERATED BY JSON, LATER (WORK IN PROGRESS) 
          WITH RANDOMIZER ONCHANGE EVENT*/}
            <Fade bottom>
              <a className="sc-randomizer" onClick={handleClick}>
                <h4 className="sc-verse">{BibleVerse.bible.verse[1]}</h4>
                <p className="sc-preach">
                  <q className="quotation">{BibleVerse.bible.preeches[1]}</q>
                </p>
              </a>
            </Fade>
          </Fade>
        </div>
        <div className="col">
          <div className="sc-mentors-container">
            <div className="mentors-container">
              <Fade bottom>
                <h4 className="sc-mentors-title">Our Mentors</h4>
              </Fade>
              {/* THIS WILL BE USING JSON SOON */}
              <Fade right cascade>
                <div className="mentors-list-container">
                  <div className="mentors-list">
                    <img src={UserIcon} alt="Profile"></img>
                    <a
                      className="mentors-text"
                      href="https://www.instagram.com/estertiranika/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <h4 className="mentors-name">Ester Tiranika</h4>
                      <p className="mentors-title">Leader</p>
                    </a>
                  </div>
                  <div className="mentors-list">
                    <img src={UserIcon} alt="Profile"></img>
                    <a
                      className="mentors-text"
                      href="https://www.instagram.com/neffy_wahyuliant0/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <h4 className="mentors-name">Nefy Wahyulianto</h4>
                      <p className="mentors-title">Co Leader</p>
                    </a>
                  </div>
                  <div className="mentors-list">
                    <img src={UserIcon} alt="Profile"></img>
                    <a
                      className="mentors-text"
                      href="https://www.instagram.com/yehezkieladolff/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <h4 className="mentors-name">Yehezkiel Aldoff</h4>
                      <p className="mentors-title">Usher Ministry</p>
                    </a>
                  </div>
                  <div className="mentors-list">
                    <img src={UserIcon} alt="Profile"></img>
                    <a
                      className="mentors-text"
                      href="https://www.instagram.com/suisandio/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <h4 className="mentors-name">Shandi Jha</h4>
                      <p className="mentors-title">Multimedia Ministry</p>
                    </a>
                  </div>
                </div>
              </Fade>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
